name: Release Packages
on:
  workflow_dispatch:
    inputs:
      positional:
        description: "VERSIONING MODE: default - changed since the last release / from-git - tagged in the current commit / from-package - latest version is not present in the registry"
        required: true
        default: "default"
        type: choice
        options:
          - default
          # https://github.com/lerna/lerna/tree/main/libs/commands/version#semver-bump
          - patch
          - minor
          - major
          # https://github.com/lerna/lerna/tree/main/libs/commands/publish#usage
          - from-git
          - from-package
      force_publish:
        description: "Force publish"
        default: false
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-packages:
    name: Release Packages
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build config packages
        run: npm run build:infra
        
      - name: Prebuild
        run: npm exec -- lerna run prebuild

      - name: Run Tests
        run: npm run test

      # if publish to github
      # - name: Setup npm auth
      #   run: |
      #     echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
      #     echo "@abelflopes:registry=https://npm.pkg.github.com" >> .npmrc
      #     echo "access=public" >> .npmrc

      # required for lerna + prebuild of packages/library/react-ck
      - name: Set git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Build
        run: npm run build

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      # if publish to npm
      - name: Setup npm auth
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          echo "access=public" >> .npmrc

      - name: Verify NPM Access
        run: npm whoami

      - name: Show git user
        run: git config --list

      - name: Run pre publish script
        run: npm exec -- lerna run prepublish --stream

      - name: Release Packages
        # https://github.com/lerna/lerna/tree/main/libs/commands/publish#readme
        run: npm exec -- lerna publish ${{ inputs.positional != 'default' && inputs.positional || '' }} --yes --no-private ${{ inputs.force_publish && '--force-publish' || '' }}

      - name: Update lockfile
        continue-on-error: true # if there are no changes to the lockfile
        run: |
          git fetch
          git pull
          npm i
          git add package-lock.json
          git commit -m "build: update lockfile [no ci]"
          git push
